name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          # نصب ابزارهای ساخت و کامپایل مورد نیاز
          sudo apt-get install -y build-essential git python3-dev libffi-dev libssl-dev
          # نصب جاوا (openjdk 8) برای ساخت اندروید
          sudo apt-get install -y openjdk-8-jdk

      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # نصب buildozer و سایر وابستگی‌های پروژه (tensorflow، kivy، numpy و ...)
          pip install cython buildozer tensorflow kivy numpy

      - name: Build APK using Buildozer
        run: |
          # پاکسازی build قبلی (اختیاری)
          buildozer android clean
          # ساخت نسخه debug از apk
          buildozer android debug
